catchat/blueprints/admin.py
from flask import Blueprint, abort
from flask_login import current_user

from ..extensions import db
from ..models import User

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/block/<int:user_id>', methods=['DELETE'])
def block_user(user_id):
    if not current_user.is_admin:
        abort(403)
    user = User.query.get(user_id)
    if not user:
        abort(400)
    db.session.delete(user)
    db.session.commit()
    return '', 204

catchat/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, logout_user, current_user, login_user

from ..extensions import db
from ..form import LoginForm, RegisterForm
from ..models import User
from ..utils import flash_errors

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.index'))
    if request.method == 'POST':
        form = LoginForm()
        if not form.validate():
            flash_errors(form)
            return redirect(url_for('.login'))
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        if user is not None:
            if user._password_hash is None:
                flash('请使用第三方登陆.')
                return redirect(url_for('.login'))
            if user.validate_password(form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('chat.index'))
        flash('用户名或密码错误!')
        return redirect(url_for('.login'))
    return render_template('auth/login.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('chat.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('chat.index'))
    if request.method == 'POST':
        form = RegisterForm()
        if not form.validate():
            flash_errors(form)
            return render_template('auth/register.html')
        user = User(email=form.email.data.lower(), nickname=form.nickname.data)
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('.login'))
    return render_template('auth/register.html')

catchat/blueprints/chat.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, abort
from flask_login import current_user
from flask_socketio import emit

from ..extensions import db, socketio
from ..form import ProfileForm
from ..models import Message, User
from ..utils import flash_errors, to_html

chat_bp = Blueprint('chat', __name__)
online_users = []


@chat_bp.route('/')
def index():
    amount = current_app.config['CATCHAT_MESSAGE_PER_PAGE']
    messages = Message.query.order_by(Message.timestamp.asc())[-amount:]
    user_amount = User.query.count()
    return render_template('chat/index.html', messages=messages, user_amount=user_amount)


@chat_bp.route('/messages')
def get_messages():
    # page = request.args.get('page', 1, int)
    count = request.args.get('count', 0, int)
    per_page = current_app.config['CATCHAT_MESSAGE_PER_PAGE']
    # pagination = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page)
    # messages = pagination.items
    messages = Message.query.order_by(Message.timestamp.desc())[count: count + per_page]
    if not messages:
        return '', 404
    return render_template('chat/_messages.html', messages=messages[::-1])


@chat_bp.route('/anonymous')
def anonymous():
    return render_template('chat/anonymous.html')


@chat_bp.route('/profile/<user_id>')
def get_profile(user_id):
    user = User.query.get(user_id)
    return render_template('chat/_profile_card.html', user=user)


@chat_bp.route('/profile', methods=['GET', 'POST'])
def profile():
    if request.method == 'POST':
        form = ProfileForm()
        if not form.validate():
            flash_errors(form)
            return render_template('chat/profile.html')
        current_user.nickname = form.nickname.data
        current_user.website = form.website.data
        current_user.github = form.github.data
        current_user.bio = form.bio.data
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('chat/profile.html')


@chat_bp.route('/message/delete/<message_id>', methods=['DELETE'])
def delete_message(message_id):
    message = Message.query.get_or_404(message_id)
    if current_user != message.author and not current_user.is_admin:
        abort(403)
    db.session.delete(message)
    db.session.commit()
    return '', 204


@socketio.on('new message')
def new_message(message_body):
    message_body = to_html(message_body)
    message = Message(body=message_body, author=current_user._get_current_object())
    db.session.add(message)
    db.session.commit()
    emit('new message',
         {'message_html': render_template('chat/_message.html', message=message),
          'message_body': message_body,
          'gravatar': current_user.gravatar,
          'nickname': current_user.nickname,
          'user_id': current_user.id},
         broadcast=True)


@socketio.on('connect')
def connect():
    global online_users
    if current_user.is_authenticated and current_user.id not in online_users:
        online_users.append(current_user.id)
    emit('user count', {'count': len(online_users)}, broadcast=True)


@socketio.on('disconnect')
def disconnect():
    global online_users
    if current_user.is_authenticated and current_user.id in online_users:
        online_users.remove(current_user.id)
    emit('user count', {'count': len(online_users)}, broadcast=True)


@socketio.on('new message', namespace='/anonymous')
def new_anonymous_message(message_body):
    avatar = 'https://www.gravatar.com/avatar?d=mm'
    nickname = '匿名'
    emit('new message',
         {'message_html': render_template('chat/_anonymous_message.html', message=message_body, avatar=avatar,
                                          nickname=nickname)},
         broadcast=True, namespace='/anonymous')

catchat/templates/chat/_anonymous_message.html
<div class="msg-box">
    <div class="picture">
        <img class="pop-card" src="{{ avatar }}">
    </div>
    <div class="msg">
        <span class="nickname">{{ nickname }}</span>
        <span class="message-body">{{ message|safe }}</span>
    </div>
    {% if current_user.is_authenticated %}
    <div class="ui icon left center pointing dropdown ellipsis-icon">
        <i class="ellipsis horizontal icon"></i>
        <div class="menu" data-offset="-33">
            <div class="item quote-button"><i class="quote left icon"></i>引用</div>
        </div>
    </div>
    {% endif %}
</div>

catchat/templates/chat/_message.html
<div class="msg-box">
    <div class="picture">
        <img class="pop-card" data-position="right center" data-offset="-40"
             data-href="{{ url_for('chat.get_profile', user_id=message.author.id) }}"
             src="{{ message.author.gravatar }}">
    </div>
    <div class="msg">
        <span class="nickname">{{ message.author.nickname }}</span>
        <small class="timestamp">{{ moment(message.timestamp).format('lll') }}</small>
        <span class="message-body">{{ message.body|safe }}</span>
    </div>
    {% if current_user.is_authenticated %}
    <div class="ui icon left center pointing dropdown ellipsis-icon">
        <i class="ellipsis horizontal icon"></i>
        <div class="menu" data-offset="-33">
            <div class="item quote-button"><i class="quote left icon"></i>引用</div>
            {% if current_user == message.author or current_user.is_admin %}
            <div class="item delete-button" data-href="{{ url_for('chat.delete_message', message_id=message.id) }}">
                <i class="delete icon"></i>删除
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>

catchat/templates/chat/_messages.html
{% for message in messages %}
    {% include "chat/_message.html" %}
{% endfor %}

catchat/templates/chat/_profile_card.html
<div class="ui items profile-card">
    <div class="item">
        <div class="ui tiny image">
            <img src="{{ user.gravatar }}">
        </div>
        <div class="content">
            <div class="header">{{ user.nickname }}</div>
            <div class="description">{{ user.bio or '这个用户很懒什么也没写.' }}</div>
        </div>
    </div>
    {% if user.github %}
        <i class="github icon"></i><a href="{{ user.github }}" target="_blank">Github</a>
    {% endif %}
    {% if user.website %}
        <i class="linkify icon"></i><a href="{{ user.website }}" target="_blank">Website</a>
    {% endif %}
    {% if current_user.is_admin and not user.is_admin %}
        <i class="delete icon"></i>
        <a class="delete-user-button" href="#!" data-href="{{ url_for('admin.block_user', user_id=user.id) }}"
           >删除</a>
    {% endif %}
</div>

catchat/templates/chat/anonymous.html
{% extends 'base.html' %}
{% block title %}匿名{% endblock %}

{% block nav %}
    <div class="ui top fixed borderless menu">
        <a class="item catchat" href="{{ url_for('chat.index') }}" title="返回">
            <img src="{{ url_for('static', filename='logo.png') }}">
            <span>CatChat(匿名)</span>
        </a>
        <div class="right menu hide-on-mobile">
            {% if not current_user.is_authenticated %}
                <div class="item">
                    <a class="ui primary button" href="{{ url_for('auth.login') }}">
                        登陆</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="pusher">
        <div class="chat-box">
            <div class="messages"></div>
        </div>
        <div class="input-area">
            <div class="ui grid form">
                <div class="ten wide column">
                    <div class="field fluid message-box">
                        {% if current_user.is_authenticated %}
                            <img class="input-avatar" src="https://www.gravatar.com/avatar?d=mm">
                            <textarea rows="2" id="message-textarea"
                                      placeholder="将内容写在这里, 并按Enter键发送."></textarea>
                        {% else %}
                            <div class="ui floating message">请<a href="{{ url_for('auth.login') }}">登陆</a>或<a
                                    href="{{ url_for('auth.register') }}">注册</a>后发送信息.
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="four wide column right floated right aligned hide-on-mobile">
                    <p>2019 ©</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script type="text/javascript">
        var socket = io('/anonymous')
    </script>
{% endblock %}

catchat/templates/chat/index.html
{% extends 'base.html' %}
{% block title %}CatChat{% endblock %}

{% block nav %}
    <div class="ui top fixed borderless menu">
        <a class="item catchat" href="{{ url_for('chat.index') }}">
            <img src="{{ url_for('static', filename='logo.png') }}">
            <span>CatChat</span>
        </a>
        <div class="item">
            <div class="ui label black basic" title="Online users">
                <i class="user icon"></i> <span id="user-count">0</span> / {{ user_amount }}
            </div>
        </div>
        <div class="right menu hide-on-mobile">
            {% if current_user.is_authenticated %}
                <div class="item">
                    <button class="ui button orange basic" id="show-snippet-modal">使用代码框</button>
                </div>
            {% else %}
                <div class="item">
                    <a class="ui primary button" href="{{ url_for('auth.login') }}">
                        登陆</a>
                </div>
            {% endif %}
            <a class="item" id="toggle-sidebar">
                <i class="sidebar icon"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="pusher">
        <div class="chat-box">
            <div class="messages">
                {% include 'chat/_messages.html' %}
            </div>
        </div>
        <div class="input-area">
            <div class="ui grid form">
                <div class="ten wide column">
                    <div class="field fluid message-box">
                        {% if current_user.is_authenticated %}
                            <img class="pop-card input-avatar" data-position="bottom left"
                                 data-href="{{ url_for('chat.get_profile', user_id=current_user.id) }}"
                                 src="{{ current_user.gravatar }}">
                            <textarea rows="2" id="message-textarea"
                                      placeholder="将内容写在这里, 并按Enter键发送."></textarea>
                        {% else %}
                            <div class="ui floating message">请<a href="{{ url_for('auth.login') }}">登陆</a>或<a
                                    href="{{ url_for('auth.register') }}">注册</a>后发送信息.
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="four wide column right floated right aligned hide-on-mobile">
                    <p>2019 ©</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script type="text/javascript">
        var socket = io()
    </script>
{% endblock %}

catchat/templates/chat/profile.html
{% extends 'base.html' %}

{% block title %}用户资料{% endblock %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <div class="ui attached message">
                <div class="header ui image ">
                    <img src="{{ url_for('static', filename='logo.png') }}" class="image">
                    <div class="content">个人信息简介</div>
                </div>
            </div>
            <form class="profile ui form attached left aligned fluid segment" method="post"
                  action="{{ url_for('chat.profile') }}">
                <div class="field eight wide">
                    <label>昵称</label>
                    <input name="nickname" placeholder="昵称" type="text" value="{{ current_user.nickname }}">
                </div>
                <div class="field">
                    <label>Github</label>
                    <input name="github" placeholder="https://github.com/yourname" type="text"
                           value="{{ current_user.github or '' }}">
                </div>
                <div class="field">
                    <label>Website</label>
                    <input name="website" placeholder="http://example.com" type="text"
                           value="{{ current_user.website or '' }}">
                </div>
                <div class="field">
                    <label>Bio</label>
                    <input name="bio" placeholder="我来自..." type="text" value="{{ current_user.bio or '' }}">
                </div>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="fields two">
                    <div class="ui orange submit fluid button">保存</div>
                </div>
            </form>
            {% for error_message in get_flashed_messages() %}
                <div class="ui message floating warning closeable">
                    <i class="close icon"></i>
                    <div>{{ error_message }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}