catchat/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, logout_user, current_user, login_user

from ..extensions import db
from ..form import LoginForm, RegisterForm
from ..models import User
from ..utils import flash_errors

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.index'))
    if request.method == 'POST':
        form = LoginForm()
        if not form.validate():
            flash_errors(form)
            return redirect(url_for('.login'))
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        if user is not None:
            if user._password_hash is None:
                flash('请使用第三方登陆.')
                return redirect(url_for('.login'))
            if user.validate_password(form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('chat.index'))
        flash('用户名或密码错误!')
        return redirect(url_for('.login'))
    return render_template('auth/login.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('chat.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('chat.index'))
    if request.method == 'POST':
        form = RegisterForm()
        if not form.validate():
            flash_errors(form)
            return render_template('auth/register.html')
        user = User(email=form.email.data.lower(), nickname=form.nickname.data)
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('.login'))
    return render_template('auth/register.html')

catchat/blueprints/chat.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, abort
from flask_login import current_user
from flask_socketio import emit

from ..extensions import db, socketio
from ..form import ProfileForm
from ..models import Message, User
from ..utils import flash_errors, to_html

chat_bp = Blueprint('chat', __name__)
online_users = []


@chat_bp.route('/')
def index():
    amount = current_app.config['CATCHAT_MESSAGE_PER_PAGE']
    messages = Message.query.order_by(Message.timestamp.asc())[-amount:]
    user_amount = User.query.count()
    return render_template('chat/index.html', messages=messages, user_amount=user_amount)


@chat_bp.route('/messages')
def get_messages():
    # page = request.args.get('page', 1, int)
    count = request.args.get('count', 0, int)
    per_page = current_app.config['CATCHAT_MESSAGE_PER_PAGE']
    # pagination = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page)
    # messages = pagination.items
    messages = Message.query.order_by(Message.timestamp.desc())[count: count + per_page]
    if not messages:
        return '', 404
    return render_template('chat/_messages.html', messages=messages[::-1])


@chat_bp.route('/anonymous')
def anonymous():
    return render_template('chat/anonymous.html')


@chat_bp.route('/profile/<user_id>')
def get_profile(user_id):
    user = User.query.get(user_id)
    return render_template('chat/_profile_card.html', user=user)


@chat_bp.route('/profile', methods=['GET', 'POST'])
def profile():
    if request.method == 'POST':
        form = ProfileForm()
        if not form.validate():
            flash_errors(form)
            return render_template('chat/profile.html')
        current_user.nickname = form.nickname.data
        current_user.website = form.website.data
        current_user.github = form.github.data
        current_user.bio = form.bio.data
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template('chat/profile.html')


@chat_bp.route('/message/delete/<message_id>', methods=['DELETE'])
def delete_message(message_id):
    message = Message.query.get_or_404(message_id)
    if current_user != message.author and not current_user.is_admin:
        abort(403)
    db.session.delete(message)
    db.session.commit()
    return '', 204


@socketio.on('new message')
def new_message(message_body):
    message_body = to_html(message_body)
    message = Message(body=message_body, author=current_user._get_current_object())
    db.session.add(message)
    db.session.commit()
    emit('new message',
         {'message_html': render_template('chat/_message.html', message=message),
          'message_body': message_body,
          'gravatar': current_user.gravatar,
          'nickname': current_user.nickname,
          'user_id': current_user.id},
         broadcast=True)


@socketio.on('connect')
def connect():
    global online_users
    if current_user.is_authenticated and current_user.id not in online_users:
        online_users.append(current_user.id)
    emit('user count', {'count': len(online_users)}, broadcast=True)


@socketio.on('disconnect')
def disconnect():
    global online_users
    if current_user.is_authenticated and current_user.id in online_users:
        online_users.remove(current_user.id)
    emit('user count', {'count': len(online_users)}, broadcast=True)


@socketio.on('new message', namespace='/anonymous')
def new_anonymous_message(message_body):
    avatar = 'https://www.gravatar.com/avatar?d=mm'
    nickname = '匿名'
    emit('new message',
         {'message_html': render_template('chat/_anonymous_message.html', message=message_body, avatar=avatar,
                                          nickname=nickname)},
         broadcast=True, namespace='/anonymous')

catchat/templates/base.html
<html lang="zh">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% block page_title %}{% endblock %} - CatChat{% endblock %}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='semantic-ui/semantic.min.css') }}">
    {% endblock %}
</head>
<body>
<div class="ui labeled icon right vertical inverted demo menu sidebar">
    <a class="item" href="{{ url_for('chat.anonymous') }}">
        <i class="user secret icon"></i>
        匿名模式
    </a>
    <a class="item" href="https://github.com" target="_blank">
        <i class="github icon"></i>
        GitHub
    </a>
    {% if current_user.is_authenticated %}
        <a class="item" href="{{ url_for('chat.profile') }}">
            <i class="setting icon"></i>
            用户资料
        </a>
    {% endif %}
    <a class="item" id="show-help-modal">
        <i class="help icon"></i>
        MD文档帮助
    </a>
    {% if current_user.is_authenticated %}
        <a class="item" href="{{ url_for('auth.logout') }}">
            <i class="power off icon"></i>
            退出
        </a>
    {% endif %}
</div>

{% block nav %}{% endblock %}

<div class="ui modal small help">
    <div class="header">Markdown 帮助</div>
    <div class="content">
        <section class="modal--default__content" id="modal-body-region">
            <div>
                <div class="modal-content">
                    <table class="ui celled striped table">
                        <tbody>
                        <tr>
                            <td><strong>粗体</strong></td>
                            <td>**粗体**</td>
                        </tr>
                        <tr>
                            <td><i>斜体</i></td>
                            <td>*斜体*</td>
                        </tr>
                        <tr>
                            <td>标题</td>
                            <td>#&nbsp;H1<br> ##&nbsp;H2<br> ###&nbsp;H3<br></td>
                        </tr>
                        <tr>
                            <td>
                                <li>列表</li>
                            </td>
                            <td>* 列表</td>
                        </tr>
                        <tr>
                            <td>引用块</td>
                            <td>&gt; 引用块</td>
                        </tr>
                        <tr>
                            <td><a href="#" target="_blank">连接</a></td>
                            <td>[title](http://...)</td>
                        </tr>
                        <tr>
                            <td>图片</td>
                            <td>![alt](http://...)</td>
                        </tr>
                        <tr>
                            <td><code>代码</code></td>
                            <td>`code`</td>
                        </tr>
                        <tr>
                            <td>
                                <div class="codehilite">
<pre><span></span><span class="k">def</span> <span class="nf">hello</span><span class="p">():
&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="k">return</span> <span class="s2">"Hello World"</span>
</pre>
                                </div>
                            </td>
                            <td style="line-height: 100%">```python <i style="color: rgba(0,0,0,0.5)">(shift+enter for
                                line break)</i><br>def hello():<br>
                                &nbsp;&nbsp;&nbsp;&nbsp;return "Hello World"<br>```
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <br>
            </div>
        </section>
    </div>
    <div class="actions">
        <button class="ui button cancel">关闭</button>
    </div>
</div>

<!-- Snippet Modal -->
<div class="ui modal small snippet">
    <div class="header">使用代码框</div>
    <div class="content">
        <div class="ui form">
            <textarea id="snippet-textarea" rows="20"></textarea>
        </div>
    </div>
    <div class="actions">
        <button class="ui button cancel">取消</button>
        <button class="ui button blue approve" id="snippet-button">发送</button>
    </div>
</div>

<!-- Mobile message Modal -->
<div id="mobile-new-message-modal" class="ui modal small">
    <div class="content">
        <div class="ui form">
            <textarea id="mobile-message-textarea" rows="15"></textarea>
        </div>
    </div>
    <div class="actions">
        <button class="ui button cancel">取消</button>
        <button class="ui button orange approve" id="send-button">发送</button>
    </div>
</div>

{% block content %}{% endblock %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='semantic-ui/semantic.js') }}"></script>
    <script src="{{ url_for('static', filename='js/forms.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-CN') }}
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        var messages_url = "{{ url_for('chat.get_messages') }}";
        var root_url = "{{ url_for('chat.index') }}";
        var current_user_id = "{{ current_user.id|default(0) }}"
    </script>
{% endblock %}

</body>
</html>

catchat/templates/errors.html
{% extends 'base.html' %}

{% block title %}{{ code }} Error{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <div class="ui attached message">
            <div class="header ui image ">
                <img src="{{ url_for('static', filename='logo.png') }}" class="image">
                <div class="content">
                    <span class="catchat-text">CatCaht</span> - {{ code }}&nbsp;&nbsp;{{ name }}
                </div>
            </div>
            <p>{{ description }}</p>
            <a class="icon" href="{{ url_for('chat.index') }}">返回主页</a>
        </div>
    </div>
</div>
{% endblock %}